<?php
// EXAMPLE ONLY. The live .treevolution-config.php is generated by GitHub Actions
// from repository secrets and is excluded from Git and denied by .htaccess.
return [
  'upload_username' => 'CHANGE-ME',
  'upload_password' => 'CHANGE-ME',
  'github_owner' => 'sccwebdesignwork',
  'github_repo' => 'treevolution',
  'github_branch' => 'main',
  'github_token' => 'FINE-GRAINED-PAT-WITH-CONTENTS-READ-WRITE',
];
