<?php
require __DIR__ . '/bootstrap.php'; auth_required();
$id=(string)($_GET['id']??''); [, $stories]=gh_get_json_file('content/stories.json'); $story=null;
foreach($stories as $s){if(story_key($s)===$id){$story=$s;break;}}
if(!$story){http_response_code(404);exit('Update not found.');}
$imgs=$story['images']??(!empty($story['image'])?[$story['image']]:[]); if(!is_array($imgs))$imgs=[];
?><!doctype html><html lang="en-GB"><head>
<link rel="icon" href="../assets/icons/favicon.ico" sizes="any">
<link rel="icon" type="image/png" sizes="32x32" href="../assets/icons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="../assets/icons/favicon-16x16.png">
<link rel="apple-touch-icon" sizes="180x180" href="../assets/icons/apple-touch-icon.png">
<meta charset="utf-8"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="../assets/css/treevolution-v6-4.css"><link rel="stylesheet" href="../assets/css/client-update.css"><title>Edit update | Treevolution</title></head><body class="client-admin"><header class="client-header"><div class="client-shell client-header-inner"><a class="client-brand" href="../"><img src="../assets/branding/treevolution-logo.svg" alt="Treevolution"></a><div class="client-header-actions"><a class="client-signout" href="../client/index.php">Dashboard</a><a class="client-signout" href="manage.php">Back to manage</a><a class="client-signout" href="logout.php">Sign out</a></div></div></header><main class="client-shell client-main"><section class="client-page-heading"><div><p class="client-kicker">Website updates</p><h1>Edit completed job</h1><p class="client-lead">Changes will update the post and its search-engine-friendly project page.</p></div></section>
<form action="update.php" method="post" enctype="multipart/form-data" class="client-update-form"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=e($id)?>">
<section class="client-panel"><div class="client-grid client-grid-3"><div class="client-field client-field-span-2"><label>Story title</label><input name="title" maxlength="90" required value="<?=e((string)$story['title'])?>"></div><div class="client-field"><label>Date completed</label><input type="date" name="date" required value="<?=e((string)$story['date'])?>"></div><div class="client-field client-field-span-2"><label>Town / area</label><input name="location" maxlength="80" required value="<?=e((string)($story['location']??'Lewes, East Sussex'))?>"><small>Town or public area only — never a customer's exact address.</small></div><div class="client-field"><label>Category</label><select name="category"><?php foreach(['Tree removal','Tree reduction','Pollarding','Hedge cutting','Stump removal','Other tree care'] as $c):?><option <?=$c===($story['category']??'')?'selected':''?>><?=e($c)?></option><?php endforeach;?></select></div></div></section>
<section class="client-panel"><div class="client-field"><label>Project story</label><textarea name="body" maxlength="1600" required><?=e((string)$story['body'])?></textarea><small>For SEO, aim for roughly 100–250 useful words: what tree, what problem, what work was carried out and the outcome.</small></div></section>
<section class="client-panel"><h2>Photographs</h2><div class="client-existing-images"><?php foreach($imgs as $i=>$img):?><label class="client-existing-image"><img src="../<?=e(ltrim((string)$img,'/'))?>" alt=""><span><input type="checkbox" name="remove_images[]" value="<?=e((string)$img)?>"> Remove photo <?=($i+1)?></span></label><?php endforeach;?></div><div class="client-field"><label>Add replacement / extra photographs</label><input type="file" name="images[]" accept="image/jpeg,image/png,image/webp" multiple><small>Maximum four photos total after removals.</small></div></section>
<section class="client-panel"><div class="client-field"><label>Photograph description</label><input name="alt" maxlength="160" required value="<?=e((string)$story['alt'])?>"></div></section>
<section class="client-publish-bar"><div><strong>Save this update?</strong><span>The project page and sitemap entry are refreshed automatically.</span></div><button class="client-button client-button-primary" type="submit">Save changes →</button></section></form></main></body></html>
